server:
  port: 8090
  servlet:
    context-path: /MusicManage
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/music?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    timeout: 1000
    jedis:
      pool:
        min-idle: 5
        max-idle: 10
        max-wait: -1
mybatis:
  type-aliases-package: com.zhangd.music.bean          #对于实体类路径
  mapper-locations: classpath:mapper/*.xml    #对应数据库xml映射文件
  configuration:
    map-underscore-to-camel-case: true  #驼峰转换
#temp files
tempFilePath: /QZiMusic/img/tempFile

#控制台打印数据库语句
logging:
  level:
    com.zhangd.music.dao: debug
